### ISSUE TITLE
Cannot include Eigen/Dense

### ISSUE THREAD

**Issue by flxinxout** [kupns-aka-kupa/setup-eigen3#2]
Hello, I have a project that uses Pybind11 to create bindings with C++ code. I need to use cibuildwheels tool to create multiple wheel files for multiple python versions and platforms.

On my CI github action, I need to add the library Eigen3, so I use this repo to do that. Here is my yaml file

```
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Eigen3
        uses: kupns-aka-kupa/setup-eigen3@v1
        id: install-eigen3
        with:
          version: 3.4.0

      - name: Check Eigen cmake module
        run: cmake --find-package -DNAME=Eigen3 -DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=EXIST

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0

        with:
          package-dir: ./impl/

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
```
The Check Eigen cmake module outputs that Eigen3 is found. But when I enter inside the build wheels, it cannot run my CMakeList file correctly, the error comes at the find_package(Eigen3 REQUIRED)

The eigen3 package is installed at /home/runner/work/dbo-criterion-eigen/dbo-criterion-eigen/Eigen3/include/eigen3

Is there an simple explanation to that? thanks!

**Comment by kupns-aka-kupa** [comment]
Hi. May i see you **w**ork**f**low minimal output or link to **wf** ? 
Your wf should have these variables after [Install Eigen3](https://github.com/marketplace/actions/setup-eigen3) execution (Tests [case output log](https://github.com/kupns-aka-kupa/setup-eigen3/actions/runs/9045449852/job/24855209425))
```yaml
env:
    Eigen3_DIR: /home/runner/work/setup-eigen3/setup-eigen3/Eigen3/share/eigen3/cmake
    Eigen3_Dir: /home/runner/work/setup-eigen3/setup-eigen3/Eigen3/share/eigen3/cmake
    PKG_CONFIG_PATH: /home/runner/work/setup-eigen3/setup-eigen3/Eigen3/share/pkgconfig
```
