### ISSUE TITLE
Windows installing fails at deps.sh

### ISSUE THREAD

**Issue by ThoreWietzke** [kupns-aka-kupa/setup-eigen3#3]
Hello,

Thanks for your actions template!
Currently my windows workflow fails when execution deps.sh. The error message is:
``` 
Run kupns-aka-kupa/setup-eigen3@v1
  with:
    version: 3.4.0
  env:
    CMAKE_GENERATOR: MinGW Makefiles
Run D:\a\_actions\kupns-aka-kupa\setup-eigen3\v1/deps.sh
  D:\a\_actions\kupns-aka-kupa\setup-eigen3\v1/deps.sh
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    CMAKE_GENERATOR: MinGW Makefiles
D:\a\_temp\72b562a8-19d0-46d3-99a3-aa29c1adbee6.sh: line 1: D:a_actionskupns-aka-kupasetup-eigen3v1/deps.sh: No such file or directory
Error: Process completed with exit code 127.
```
My complete workflow is as follows:
```
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.11"]
        include:
          - gen: MinGW Makefiles
            os: windows-latest
          - gen: Unix Makefiles
            os: ubuntu-latest

    steps:
    - name: Checkout and init submodules
      uses: actions/checkout@v4

    - name: Install Eigen3
      uses: kupns-aka-kupa/setup-eigen3@v1
      with:
        version: 3.4.0
      env:
        CMAKE_GENERATOR: ${{ matrix.gen }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install .
```

The ubuntu worker works fine though.

**Comment by kupns-aka-kupa** [comment]
Hi 👋. Use master version of workflow.

```yaml
- name: Install Eigen3
      uses: kupns-aka-kupa/setup-eigen3@master
      with:
        version: 3.4.0
      env:
        CMAKE_GENERATOR: ${{ matrix.gen }}
```

V1 works only on Linux. 
V2 publish hands do not reach
